### PR TITLE
Rename the ingestion-team

### PR DESCRIPTION
**Pull request by tutelaris**
### Description
As part of the GitHub teams renaming initiative, it's required to rename the @elastic/ingestion-team to @elastic/search-extract-and-transform.

This PR is dedicated to renaming @elastic/ingestion-team to @elastic/search-extract-and-transform

### CODE REVIEW

**Comment by jedrazb** [comment]
buildkite test this

**Review by jedrazb — APPROVED** [review]

**Comment by jedrazb** [comment]
@elasticmachine merge upstream

**Comment by jedrazb** [comment]
Trying to trigger the buildkite job for us...

**Comment by tutelaris** [comment]
buildkite test this

**Comment by jedrazb** [comment]
buildkite test this

**Pull request merged**
